### ISSUE TITLE
原 `episodes.jsonlines` 现改名为 `episode.jsonlines`？

### ISSUE THREAD

**Issue by jerrylususu** [bangumi/Archive#3]
似乎先前 releases 里提供的 `dump.zip` 中分集数据文件名为 `episodes.jsonlines` （复数 s），当前最新文件中为 `episode.jsonlines` （单数）。请问以后数据中是否都会按此修改？

downstream ref: https://github.com/jerrylususu/bangumi-takeout-py/issues/13

**Comment by Trim21** [comment]
应该是之前重写导出脚本的时候不小心修改了。之前没考虑会有自动化脚本自动提取数据的情况…

后面就固定现在的文件名吧
