### ISSUE TITLE
可否在 subject.jsonlines 中增加条目图片 URL？

### ISSUE THREAD

**Issue by wzyboy** [bangumi/Archive#4]
我正在写一个根据 Bangumi 上的信息生成 nfo 文件的东西，类似于 [dantalian](https://github.com/nanozuki/dantalian)，不过是从本地数据源读取。dantalian 对每个番组用多个 API 请求抓了非常详细的信息，但大部分我其实不需要。如果 `subject.jsonlines` 中有条目图片的 URL 的话，我就可以完全用本地数据源生成 nfo 了。

还请考虑一下，将条目图片 URL 加入导出中，感谢…

**Comment by trim21** [comment]
https://bangumi.github.io/api/#/%E6%9D%A1%E7%9B%AE/getSubjectImageById

**Comment by wzyboy** [comment]
赞，原来只要一个请求就可以了…感谢！
