### ISSUE TITLE
Release 信息中的文件名不对

### ISSUE THREAD

**Issue by kookxiang** [bangumi/Archive#8]
https://github.com/bangumi/Archive/releases

Release 中写的是 `dump-2024-08-30 164231Z.zip`，实际上是 `dump-2024-08-30.164231Z.zip`

> latest dump filename: dump-2024-08-30 164231Z.zip
> {"filename": "dump-2024-08-30 164231Z.zip", "updated_at": "2024-08-30 16:42:31Z", "unix": 1725036151}

> https://github.com/bangumi/Archive/releases/download/archive/dump-2024-08-30.164231Z.zip

**Comment by trim21** [comment]
用这个文件吧，会自动更新。 https://github.com/bangumi/Archive/blob/master/aux/latest.json
